- hosts: all
  become: yes
  become_method: sudo
  user: centos
  tasks:

  - name: Install Part_1
    include_tasks: part_1.yml
    when: "'ELK-Kibana' in inventory_hostname"


  - name: Install Part_2
    include_tasks: part_2.yml
    when: "'ELK-Remote' in inventory_hostname"

  
