- hosts: all
  become: yes
  become_method: sudo
  user: centos
  tasks:

  - name: Install Part_1
    include_task: part-1.yml
      
    when: "ansible_default_ipv4.address == '54.144.156.177'"


  - name: Install Part_2
    include_task: part-2.yml
    
    when: "ansible_default_ipv4.address == '52.5.223.46'"

  
